LED6 SEGMENT CODE
rseg LED6

; 包含表定义
$INCLUDE (led6_tables.inc)
$INCLUDE (../user/CONFIG.INC)

PUBLIC LED6_Refresh
PUBLIC LED6_ApplyTable

; LED6_Refresh: 在 ISR 中被调用，快速输出当前缓冲的单位
LED6_Refresh:
    MOV P0, #0FFh
    MOV P2, #00h

    MOV A, 038h
    MOV R2, A
    ADD A, #030h
    MOV R0, A
    MOV A, @R0        ; 读 Buffer
    MOV B, A

    MOV DPTR, #SEG_TABLE
    MOV A, B
    MOVC A, @A+DPTR
    MOV B, A

    MOV DPTR, #BITMASK_TABLE
    MOV A, R2
    MOVC A, @A+DPTR
    MOV R1, A

    MOV A, B
    MOV P0, A
    MOV A, R1
    MOV P2, A

    INC 038h
    MOV A, 038h
    CJNE A, #06, LED6_EXIT ; 6 位数码管
    MOV 038h, #00h

LED6_EXIT:
    RET

; LED6_ApplyTable
; 输入: A = 表 ID
; 映射：
;   00h TABLE_DISPLAY_INIT_BLANK
;   01h TABLE_DISPLAY_RUN_BLANK
;   02h TABLE_MENU_MAIN_OPT
;   03h TABLE_OPT_ERR011
;   04h TABLE_OPT1_PROMPT
;   05h TABLE_OPT2_PROMPT
;   06h TABLE_OPT3_PROMPT
;   07h TABLE_PASS_PROMPT
;   08h TABLE_PASS_ERROR_FALSEX
;   09h TABLE_PASS_ERROR_LOCKED
LED6_ApplyTable:
    PUSH ACC
    PUSH B
    PUSH DPL
    PUSH DPH

    ; 选择表地址
    CJNE A, #00h, LBL_L1
    MOV DPTR, #TABLE_DISPLAY_INIT_BLANK
    SJMP LBL_COPY
LBL_L1: CJNE A, #01h, LBL_L2
    MOV DPTR, #TABLE_DISPLAY_RUN_BLANK
    SJMP LBL_COPY
LBL_L2: CJNE A, #02h, LBL_L3
    MOV DPTR, #TABLE_MENU_MAIN_OPT
    SJMP LBL_COPY
LBL_L3: CJNE A, #03h, LBL_L4
    MOV DPTR, #TABLE_OPT_ERR011
    SJMP LBL_COPY
LBL_L4: CJNE A, #04h, LBL_L5
    MOV DPTR, #TABLE_OPT1_PROMPT
    SJMP LBL_COPY
LBL_L5: CJNE A, #05h, LBL_L6
    MOV DPTR, #TABLE_OPT2_PROMPT
    SJMP LBL_COPY
LBL_L6: CJNE A, #06h, LBL_L7
    MOV DPTR, #TABLE_OPT3_PROMPT
    SJMP LBL_COPY
LBL_L7: CJNE A, #07h, LBL_L8
    MOV DPTR, #TABLE_PASS_PROMPT
    SJMP LBL_COPY
LBL_L8: CJNE A, #08h, LBL_L9
    MOV DPTR, #TABLE_PASS_ERROR_FALSEX
    SJMP LBL_COPY
LBL_L9: CJNE A, #09h, LBL_DEFAULT
    MOV DPTR, #TABLE_PASS_ERROR_LOCKED
    SJMP LBL_COPY
LBL_DEFAULT:
    ; 未知 ID -> 使用空白表
    MOV DPTR, #TABLE_DISPLAY_INIT_BLANK

LBL_COPY:
    MOV R0, #035h    ; 指向 035h，逐字写入到 035..030
    MOV R3, #00h
LBL_LOOP:
    MOV A, R3
    MOVC A, @A+DPTR
    MOV @R0, A
    DEC R0
    INC R3
    MOV A, R3
    CJNE A, #06, LBL_LOOP

    POP DPH
    POP DPL
    POP B
    POP ACC
    RET

END
